# Generated by Django 4.1 on 2022-09-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patients',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
